### ISSUE TITLE
使用 KODI 14.2 安裝 chinese keyboard 鍵盤選項沒有 chinese keyboard

### ISSUE THREAD

**Issue by cywang2gg** [taxigps/script.module.keyboard.chinese#3]
您好: 

原本使用 Kodi 14.0內建中文輸入法安裝版本. 最近更新到 14.2. 
安裝您的 xbmc-addons-chinese or chinese keyboard addon, 在鍵盤選項沒有 chinese keyboard.
請問是有需要注意的地方嗎?

**Comment by taxigps** [comment]
中文输入插件用于中文插件库中的插件，非Kodi本身。

**Comment by cywang2gg** [comment]
所以是安裝 repository.xbmc-addons-chinese-1.2.0.zip 然後啟用 中文鍵盤, 是這樣嗎? 感謝
